### ISSUE TITLE
pip prevents admins from making requests for users

### ISSUE THREAD

**Issue by merchang** [inst-support-eng/panda-pto#59]
1. as admin/sup, navigate to a user page
2. toggle user to pip = 1
3. attempt to make a request on behalf of the user

**Comment by BlinkVonDoom** [comment]
https://github.com/inst-support-eng/panda-pto/blob/636bf779bff3db2bb69521b0c615487064a4c461/app/controllers/pto_requests_controller.rb#L44

should include logic to check if requestor is same as user id on the request
